### ISSUE TITLE
User can task the system with emailing participants with their matches

### ISSUE THREAD

**Issue by jonodrew** [jonodrew/mentor-match#100]
A user should be able to task the system to email all participants

They will need to provide:
- their api key, to prevent misuse
- the template id of the email they want to send
- the reply to id

**Comment by jonodrew** [comment]
#101 will partly close this issue. @johnpeart , could you also do a new HTML page with a form that asks for the above, preferably as 

`api-key`, `template-id`, and `reply-id`?

**Comment by johnpeart** [comment]
This has been done!
See #104 for details and screenshot below.

![Screenshot 2022-06-25 at 12 43 27](https://user-images.githubusercontent.com/4903081/175772097-9005bb61-32f4-4503-b087-eaa9ee8c3d8e.png)
