### ISSUE TITLE
Cookies policy update

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#103]
# Issue

The new functionality added to allow a user to select the matching algorithm they want relies upon a new cookie.
This cookie is not reflected in the cookie policy.

# Proposed solution

In the `cookies.html` page template, add info on the new cookie.

**Comment by johnpeart** [comment]
@jonodrew I believe my assessment is correct?
It's based on the below code from the `routes.py` file:

```python
@main_bp.route("/options", methods=["GET", "POST"])
def options():
    if request.method == "GET":
        return render_template("options.html")
    else:
        matching_function = request.form.get("radios--outcomes", "quality")
        response = make_response(redirect(url_for("main.process")))
        response.set_cookie(
            "matching_func",
            matching_function,
            expires=datetime.datetime.now() + timedelta(minutes=30),
        )
        return response
```

I think a new 'matching_func' cookie has been created?

If this is correct, I will do a PR to update the cookies page.

**Comment by jonodrew** [comment]
Yes, that's right! Thanks for catching it
