### ISSUE TITLE
User can download CSV

### ISSUE THREAD

**Issue by jonodrew** [jonodrew/mentor-match#19]
Does the user need to download the CSV? Or simply receive it?

Currently the system sends the input files to the celery worker. This means that the long-lasting processing can happen behind the scenes. However, sending the files back is almost impossible - because nothing is waiting for a response. The webserver is single-threaded - that's why we're using celery to do the processing. So, the options become:

1. User is emailed the file <-- requires integration with an email service
2. Mentors/mentees are emailed direct without intervention from the manager <-- how much can the process be trusted?
2. The celery container copies the files across the network to the flask container (not sure how)
3. Something something javascript? Maybe a long-running process on the client that polls the celery task?

I like 1. the best, because even though it means an integration it means not messing around with things behind the scenes

**Comment by jonodrew** [comment]
@johnpeart What do you think?

**Comment by johnpeart** [comment]
**On option 1:**
That's potentially a lot of personal data floating around in a single email. How would you ensure it was securely delivered and (relatively) not tampered with?

**On option 2:** 
This feels like a neater option for the initial process, **but** it's not just one email that needs to be sent. 
There are follow up emails, reminders, etc.

To facilitate that, presumably you'd need to store the data for a period and keep the system chugging along. You'd also need the ability to remove people from the process if they dropped out for whatever reason, so it's not as simple as just scheduling some emails for x weeks in advance and leaving it.

So I think on balance Option 1 is better than Option 2.

Option 4 strikes me as a potentially useful compromise position, but the question is do we collectively know how to poll the backend system using client-side JS?

**Comment by jonodrew** [comment]
On 1 - you can't guarantee delivery unfortunately. Securely - well, it would be sent as an attachment with a provider (Twilio, Notify, etc) so then it's a question of how much we trust those providers. 

On 4 - I can certainly give it a try, but it's not something I've done before so it might all go sideways 😆

**Comment by johnpeart** [comment]
**On option 1:** 
My bigger concern is that email is (generally) not encrypted, and you'd want encrypted data to keep people's details safe.
Is there a way of encrypting the file contents, such that it only opens with a password set by the user on upload?

So the chain would be:

1. Upload file to the site
2. Site asks for a password
3. Click 'go'
4. System does matching
5. System finishes matching, creates encrypted file (CSV inside a ZIP?)
6. Email sent with encrypted attachment
7. User downloads attachment
8. Attachment not accessible without password from step 2

Is that better and Option 4?

**Comment by jonodrew** [comment]
For now I'm working on option 4, on the assumption that the user doesn't mind sticking around for a couple of minutes.

Option 1 - there's a lot happening there. I think it would be possible to encrypt the file and then send it, but I also wonder if I've over-complicated it - it shouldn't take longer than a couple of minutes and we could flash up a thing that says "Please don't close this window!"

**Comment by jonodrew** [comment]
Alright, new plan. Work out how to OAuth with Google and just jam the finished file in there. Done

**Comment by jonodrew** [comment]
#26 fixes this issue
