### ISSUE TITLE
Proposal: Add data collection

### ISSUE THREAD

**Issue by jonodrew** [jonodrew/mentor-match#25]
# Proposal to add database and data collection to this service

## Recommendation 
Add a form to this service to ease data collection and data processing

## Context
1. Currently data is collected via another service and brought into this service via a CSV. This involves downloading and then uploading data, increasing the number of places this sensitive data is stored. 
2. This service is run using the Heroku free tier, which limits the number of servers that can be run. This service uses the maximum, two, as required by the architecture.

### Maintain this approach
1. This approach does work well. It costs almost nothing, aside from the time and love of volunteers. The code is entirely set up to use CSVs and, although it could be changed, it would come at the cost of not developing something else.
2. Developing a form through another service like Google Forms allows flexibility for non-technical colleagues, although alterations to the form would also inevitably require alterations to the code - so this is a weak reason to maintain this approach
3. The chain of custody and control of a file is easy to maintain, particularly if the data is collected with a tool like Google Forms. Auditing who has accessed what data can be done natively. That would not necessarily be the case with a database

### Move to data collection in-app
1. Data collection within the app reduces the risk of data loss somewhere along the process of collection and re-uploading
2. Data stored in a cloud-based database is encrypted at rest and not accessible to anyone without the necessary permissions

**Comment by johnpeart** [comment]
Just a thought on the second option (move to data collection in-app); would this limit the ability of a third party (say, another Civil Service employee network) to use the tool? 

The advantage of a separate registration process and a separate matcher is that, provided a third party used the same methods we did to undertake matching, they could benefit from the tool with no additional work from us and no additional work from them to customise it.

What do you think?

**Comment by jonodrew** [comment]
Interesting!

So: probably. Adding a database is reasonably simple, and using heroku or digital ocean I can set up a one-click deployment that'll manage the creation of those resources at the backend. The difficult thing is setting the database up with the questions - there would need to be some kind of setup process/installation wizard that asked people what their questions were going to be, and then how they'd be compared, and so on, and so on.

The alternative is running a single instance, keeping all user data and questions and comparisons together (on an encrypted database, of course) and running it as SaaS. However, those costs would increase very sharply, and at that point my friend we are running a business.

So I think for now this is not something I'll do. But for future me, here's a rough outline of the approach.

- as is
- users able to specify their own weights for the matching score
- users able to map the fields in their CSV to the required fields in the software
- users able to create their own fields, with weightings and basic checks (eg is the same as, is not the same as)
- users able to create their own fields with complex processing
