### ISSUE TITLE
Proposal: Privacy policy

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#47]
# Recommendation

Add a cookie consent prompt and privacy policy statement.

# Context

The tool uses cookies to work. The tool may also require broader analytics collection. As a result, we may need a cookie consent / privacy policy to make it transparent how the data is being processed.

# Options

1. **Do nothing**. It's not entirely clear that this is required as we're not a company putting this together but private individuals. Moreover, the data being processed will be data that we already have explicit consent to process, and the only people using this tool will be people that specifically know what it does and what it's for.
2. **Add a cookie consent banner**. Following the [GOV.UK design system example](https://design-system.service.gov.uk/components/cookie-banner/) we could add a cookie banner and limit the policy statement to the cookies required to operate the tool.

# Dependencies / steps

- [ ] Establish what cookies the site uses
- [ ] Draft the policy statement
- [ ] Add the banner

**Comment by johnpeart** [comment]
@jonodrew any thoughts on this?

I can handle the policy angle but I don't have the skills to do the code!

**Comment by jonodrew** [comment]
I'm hopeful that we won't need it for cookies. One piece of data is set, which is a random string to identify which files to process. No user data (other than the files!) is captured at the moment, and I'm a bit squeamish about collecting anything at all.

I think it's a good idea to be transparent about what we do with the data, though, so users can make an informed decision about whether they want to proceed.

**Comment by johnpeart** [comment]
In which case, I think I can handle this from the front-end perspective, you'll just need to help fill in the blanks on the policy.

I'll create a branch for this shortly...

**Comment by johnpeart** [comment]
I've started a `cookies` branch to do this. 

Having read the guidance a bit more closely from the GOV.UK Design System, if we are confident there are no non-essential cookies then we do not need a 'consent banner'; instead, we can just link to a page from the site footer.

So the tasks are:

- [x] Add a footer link
- [ ] Add a `/cookies` page 
- [ ] Write a policy

**Comment by johnpeart** [comment]
@jonodrew I've created a PR to merge in the page templates; the policy will need to be written later.
