### ISSUE TITLE
Proposal: Start page

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#49]
# Recommendation

Add a 'Start page' before the main tool.

# Context

People are not good at computers. Users might need help understanding what this tool is for and how it works. Getting things right with design requires proper user research and we don't have the ability to do that. So let's steal from best practice!

# Options

1. **Do nothing** – see if people figure it out themselves!
2. **Add help text similar to the [CS LGBT+ Network tools](https://www.civilservice.lgbt/tools) pages** – add a summary/details block at the top of the tool that users can expose
3. **Add a start page like on [GOV.UK services](https://design-system.service.gov.uk/patterns/start-pages/)** – add a separate preceding page before users see the tool

Option 3 provides greater ability to simplify the journey, and could also make it easier to sign post the privacy/cookies policy (see #47).

# Next steps

- [ ] Add a page
- [ ] Update the [CS LGBT+ Network design system](https://www.civilservice.lgbt/design-system) to include a Start button
- [ ] Draft the text
- [ ] Link from Start Page to the tool

**Comment by johnpeart** [comment]
@jonodrew per our discussion on pull request #48; this is how I'd propose moving forward with the 'about this tool' type text.

I can do steps 2 to 4; how do you add a page such that the `index.html` page is now the Start Page, and the tool becomes something like `/matcher.html`

**Comment by jonodrew** [comment]
I love this idea! So I'd propose:

- `start with the index page, which has the route `/`. This will have the "Start" content and button, and lead to:
- upload page, where people will upload their docs - I will need to do some work on the html page so our web server recognises that they're files
- a "process" page, where we'll move the javascript you wrote that does the updating and add a button that says "process"

Does that all make sense? I think we could break each of these into their own feature branch

**Comment by jonodrew** [comment]
Let's pair on it this week - I can walk you through creating new routes
