### ISSUE TITLE
Proposal: domain name

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#52]
# Issue

We need to put this on a proper domain.

# Options

- mentor-matcher.civilservice.lgbt
- mentor-match.civilservice.lgbt
- mentoring.civilservice.lgbt

**Comment by johnpeart** [comment]
Any thoughts @jonodrew?

**Comment by jonodrew** [comment]
Putting it on a subdomain might need some extra work to make sure the routes and so are all right. Can we park this for the moment until we've finished version one?

**Comment by jonodrew** [comment]
I like mentoring.civilservice.lgbt, I think it does what it says on the tin.

If we were going full gov.uk we'd go mentoring.service.civilservice.lgbt, but I think that's actually more confusing, not less!

**Comment by johnpeart** [comment]
OK. Just let me know where to point the DNS. Related question: is the deployed site served over HTTPS?

**Comment by jonodrew** [comment]
It depends on the certificate for civilservice.lgbt - if it's a wildcard certificate (`*.civilservice.lgbt`) then yes, the subdomain mentoring.civilservice.lgbt will be served over HTTPS. If not, we'd need to either change the certificate or get a new one just for the subdomain. I'd rather change the certificate!

**Comment by jonodrew** [comment]
Right, so there's a small issue here where Heroku doesn't allow Free tier users to use their own certificates: https://devcenter.heroku.com/articles/ssl#dynos-and-certificate-options

So I would say our options are:
- pay a bit to Heroku
- migrate this whole thing to AWS and see if we can make it work at the free tier there
- er
- I think that's it, really

**Comment by johnpeart** [comment]
Ah bugger. 

Is there a way of doing this using GitHub Actions? 
If not, I’ll need to do a business case to get some more cash. I can probably only justify it if we can get some other networks to use it, mind you.

**Comment by jonodrew** [comment]
Bugger with bells on it

GitHub Actions is just the continuous integration/deployment. No way of hosting it there.

We talked about offering it out to other networks - I think there'll be plenty of work to do first to make it more flexible, though. Worth setting up some meetings/chats?

Surely we can justify that your time is worth more than £156 a year!

**Comment by johnpeart** [comment]
OK, on the basis that it is currently possible to download the code and run the service locally, let's consider this 'version 1', with the SSL issues being for the next iteration alongside other changes and tweaks.

I'll set up a `mentoring.service.civilservice.lgbt` domain (I think including the `service` is advisable as it may become the first of many!) if you can let me know where to point it. We can then call this quits until we can battle plan phase 2.

**Comment by jonodrew** [comment]
This is the guide for setting up the custom domain if we leave it where it is: https://devcenter.heroku.com/articles/custom-domains

However, I'm not sure it's a good idea to publish it without encryption - people shouldn't be passing personal data to an unencrypted service. I guess we can show it off, but it should come with a big old warning that it's not safe. It's a real heartbreak to have got to this point and not to be able to share it around, but we should be responsible with the offering.

**Comment by johnpeart** [comment]
Can we pop it behind a log in for now?
That way, only we know it's there and we'll know not to use it yet.

**Comment by jonodrew** [comment]
Yes, I can do that. Couple of days depending on what else I've got on. Nice solution!

**Comment by johnpeart** [comment]
I've added the domain name to the registrar end and also the Heroku dashboard now... (better late than never!)
`mentoring.service.civilservice.lgbt`
