### ISSUE TITLE
Clicking the download button twice crashes the server

### ISSUE THREAD

**Issue by jonodrew** [jonodrew/mentor-match#55]
Because the server deletes the files once they've been served, users can cause an error if they click the download button again.

Options:
- ignore multiple clicks
- only allow one click and then close the dialog, or deactivate the button

@johnpeart which do you think is better for users?

**Comment by johnpeart** [comment]
I think it would be better to deactivate the button.
We could can add a disabled class to the button and change the text on the button to 'Download completed'?

**Comment by jonodrew** [comment]
That sounds good! I'll pop this in the baclog then and we can get to it when we get to it. Let's do it after finishing #57 so it's in the right place (or alternatively, we can move the dialog to its own file and then pull it in where we need it)

**Comment by johnpeart** [comment]
@jonodrew Having reflected on this further, should we:

1. Remove the dialog entirely – it doesn't work in all browsers anyway – then
2. Add a separate 'download' page, and 
3. Once the button is clicked, redirect the user to a 'finished' page

**Comment by jonodrew** [comment]
I like these ideas. The redirect would need to be via javascript, because that's what's polling the task at the backend. I might need your help with that. Then we can have a download page with a bit of info that says how long the data will be kept if it's now downloaded, and then as you say the finished page. 

To note that while the data is available, anyone going to that link could download the data. However, given that it's described by a long random string, I think we can be confident that it's not guessable

Resolving this will impact #64 I think

**Comment by johnpeart** [comment]
@jonodrew I've created a draft pull request that makes a start on this; grateful for your additional input as I've taken it about as far as I can fathom on my own!

**Comment by johnpeart** [comment]
I think the changes made in #65 resolve this problem by default?

**Comment by jonodrew** [comment]
Closed by #65
