### ISSUE TITLE
Clicking the 'close dialog' doesn't delete the matching data

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#64]
# Steps to reproduce

1. Upload two files on `/upload`
2. Select 'Start matching' on `/process`
3. On the dialog, *don't* click 'Download matches' and instead just click 'Close dialog'

# Expected behaviour

The matching data show *always* be deleted whether the user:
 - clicks the download button
 - clicks the close button
 - closes the window without action

Or if the user takes no action:
- after a certain time limit

**Comment by johnpeart** [comment]
@jonodrew what do you think to this one? 
Think I'll have to leave this one to you as it's beyond my abilities to link this all together!

**Comment by jonodrew** [comment]
Given we've got rid of the dialog, what's the expected behaviour now? The user still has a choice about whether or not to download the data, so we should set some kind of deletion period right?

**Comment by johnpeart** [comment]
The same problem still exists with the download page; if a user doesn't click download, then the data doesn't delete.
I think the solution has to be a timed expiry on the server side to purge the data if it's still there after, say, 15 minutes after it's been generated?

**Comment by jonodrew** [comment]
Closed by #697
