### ISSUE TITLE
Update privacy policy

### ISSUE THREAD

**Issue by johnpeart** [jonodrew/mentor-match#84]
# Issue

The privacy policy reflects the data used in the first round of the programme. The new programme works slightly differently so the policy should be updated.

# Recommendation

The following changes should be made:

## Special category data

Amend the following text from the existing policy:

> No special category data is collected as part of the programme, and so this service does not process any special category data.

Replace it with:

> Special category data is collected as part of the programme. This service processes special category data in order to make the programme function. Where special category data is collected and processed, explicit consent has been gained from the data subject.

## Changes to this policy

Amend the following text from the existing policy:

> This policy was last updated on 21 February 2022.

Replace it with:

> This policy was last updated on ( insert relevant date )

As the service is not yet in use officially, I don't propose to publish a related data notice.

**Comment by jonodrew** [comment]
Did you ever make a PR for this @johnpeart ?

**Comment by johnpeart** [comment]
I did not!
But I have now.
